version: "3.3"
services:

  #POSTGRES
  leaderdb:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kk
    ports:
      - "5435:5435"
    networks:
      - mesh
    volumes:
      - leaderdb:/var/lib/postgresql/data

  #KAFKA DEP
  kafka:
    image: confluentinc/cp-kafka:6.2.4
    restart: always
    depends_on:
      - zookeeper
    networks:
      - mesh
    ports:
      - "9092:9092"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_CONTAINER:PLAINTEXT
      KAFKA_ADVERTIESED_LISTENERS: PLAINTEXT://127.0.0.1:9092, PLAINTEXT_CONTAINER://kafka:29092
      KAFKA_OFFEST_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka:/var/lib/kafka

  kafka-init:
    image: confluentinc/cp-kafka:6.2.4
    depends_on:
      - kafka

    networks:
      - mesh
    entrypoint: ["/bin/sh", "-c"]
    command: |

    # blocks until kafka is reachable
	kafka-topics --bootstrap-server kafka:29092 --list

    echo -e 'Creating kafka topics'
    kafka-topics --boostrap-server kafka:29092 --create --if-not-exists --replication-factor=2 --parititions=12 --topic kk.enhancement

    echo -e 'Successfully created the following topics:'
    kafka-topics --bootstrap-server kafka:29092 --list


    # Metrics Collection
  graphite:
      image: graphiteapp/graphite-statsd:1.1.10-1
      restart: always
      networks:
        - mesh
      ports:
        - "8080:80"
        - "8125:8125/udp"
        - "8126:8126"
        - "2003:2003"
        - "2004:2004"

    # Metrics UI - (UN/PM: admin/admin)
  grafana:
    image: grafana/grafana:8.3.7
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mesh
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - graphite

networks:
  mesh: {}

volumes:
  leaderdb:
  grafana:
  kafka:
  zookeeper:
