// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package storage

import (
	"database/sql"
	"time"
)

type Category struct {
	CatID   int32  `json:"cat_id"`
	CatName string `json:"cat_name"`
}

type Transaction struct {
	TaID                 int32           `json:"ta_id"`
	TaPostdate           time.Time       `json:"ta_postdate"`
	TaDescription        string          `json:"ta_description"`
	TaDebit              sql.NullFloat64 `json:"ta_debit"`
	TaCredit             sql.NullFloat64 `json:"ta_credit"`
	TaBalance            float32         `json:"ta_balance"`
	TaClassificationText string          `json:"ta_classification_text"`
	CatID                sql.NullInt32   `json:"cat_id"`
}
