// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transaction (postdate, description, debit, credit, balance, classification_text) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTransactionParams struct {
	Postdate           time.Time
	Description        string
	Debit              sql.NullFloat64
	Credit             sql.NullFloat64
	Balance            float32
	ClassificationText string
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransaction,
		arg.Postdate,
		arg.Description,
		arg.Debit,
		arg.Credit,
		arg.Balance,
		arg.ClassificationText,
	)
	return err
}
